In [1]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re

import warnings
warnings.filterwarnings('ignore')

In [2]:
# PATH = 'C:\Program Files (x86)\chromedriver.exe' #extracting path of the webdriver
# driver = webdriver.Chrome(PATH)

In [3]:
driver = webdriver.Chrome(r'c:\Users\Bawla Singh.DESKTOP-KT1PI9D\Desktop\chromedriver.exe')
driver=webdriver.Chrome('chromedriver.exe')

* Q1: Write a python program to scrape data for “Data Analyst” Job position in 
“Bangalore” location. You have to scrape the job-title, job-location, company_name,
experience_required. You have to scrape first 10 jobs data.
This task will be done in following steps:
1. first get the webpage https://www.naukri.com/
2. Enter “Data Analyst” in “Skill,Designations,Companies” field and enter “Bangalore” 
in “enter the location” field.
3. Then click the search button.
4. Then scrape the data for the first 10 jobs results you get.
5. Finally create a dataframe of the scraped data.

In [4]:
url = "https://www.naukri.com/"
driver.get(url)

In [5]:
# entering “Data Analyst” in “Skill,Designations,Companies” field and enter “Bangalore” in “enter the location” field.
search_field_designation=driver.find_element_by_class_name("suggestor-input ") #job search bar
search_field_location=driver.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[3]/div/div/div/input') #location search bar
search_field_designation.send_keys("Data Analyst")
search_field_location.send_keys("Bangalore")


# clicking the search button
search_button=driver.find_element_by_xpath("/html/body/div/div[2]/div[3]/div/div/div[6]")
search_button.click()

time.sleep(4)

# creating empty lists for scraping data
job_title=[]
job_location=[]
company_name=[]
experience_required=[]

#scraping the job-titles
titles=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
for i in titles:
    if i.text is None :
        job_title.append("--") 
    else:
        job_title.append(i.text)

time.sleep(4)
#scraping the job-location
locations=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
for i in locations:
    if i.text is None :
        job_location.append("--") 
    else:
        job_location.append(i.text)
        
time.sleep(4)        
#scraping the company_name 
companies=driver.find_elements_by_xpath("//div[@class='mt-7 companyInfo subheading lh16']/a")
for i in companies:
    if i.text is None :
        company_name.append("--") 
    else:
        company_name.append(i.text)
company_name[0:2]


time.sleep(4)
#scraping the experience_required 
experience=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span[1]")
for i in experience:
    if i.text is None :
            experience_required.append("--") 
    else:
            experience_required.append(i.text)


time.sleep(4)
# creating the dataframe from the scraped data and taking only first 10 jobs
df=pd.DataFrame({"experience_required":experience_required[0:10],"company_name":company_name[0:10],"job_location":job_location[0:10],
                "job_title":job_title[0:10]})
df

,experience_required,company_name,job_location,job_title
0,0-1 Yrs,FUTURLYTIC PRIVATE LIMITED,Bangalore/Bengaluru(Hebbal Kempapura),Data Analyst For Text / Sentiment Analysis
1,1-6 Yrs,Dell,Bangalore/Bengaluru,Senior Data Analyst (Digital Services Analytics)
2,2-7 Yrs,(2067 Reviews),"Hyderabad/Secunderabad, Bangalore/Bengaluru",Data Analyst / BI Analytics Consultant - Night...
3,12-15 Yrs,Oracle,Bangalore/Bengaluru,"Lead - Data Analyst / Scientist ( R, Qlik, Pow..."
4,0-3 Yrs,(2896 Reviews),"Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab...",Junior Data Analyst/ Scientist- Fresher Position
5,2-4 Yrs,Axim Technologies,Bangalore/Bengaluru,Senior Data Analyst III
6,3-7 Yrs,Sejal Consulting Hub,Bangalore/Bengaluru,Senior Data Analyst
7,4-9 Yrs,Flipkart,Bangalore/Bengaluru,Data Analyst (Digital Services Analytics)
8,8-10 Yrs,(5741 Reviews),Bangalore/Bengaluru,Data Analyst
9,3-8 Yrs,Flipkart,Bangalore/Bengaluru,Business Data Analyst

* Q2: Write a python program to scrape data for “Data Scientist” Job position in
“Bangalore” location. You have to scrape the job-title, job-location,
company_name. You have to scrape first 10 jobs data.
This task will be done in following steps:
1. first get the webpage https://www.naukri.com/
2. Enter “Data Scientist” in “Skill,Designations,Companies” field and enter
“Bangalore” in “enter the location” field.
3. Then click the search button.
4. Then scrape the data for the first 10 jobs results you get.
5. Finally create a dataframe of the scraped data.

In [6]:
url = "https://www.naukri.com/"
driver.get(url)
time.sleep(6)

In [7]:
# entering “Data Scientist” in “Skill,Designations,Companies” field and enter “Bangalore” in “enter the location” field.

search_field_designation=driver.find_element_by_class_name("suggestor-input ")   #job search bar
search_field_location=driver.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[3]/div/div/div/input')  #location search bar
search_field_designation.send_keys("Data Scientist")
search_field_location.send_keys("Bangalore")


# clicking the search button
search_button=driver.find_element_by_xpath("/html/body/div/div[2]/div[3]/div/div/div[6]")
search_button.click()

In [8]:
# creating empty lists for scraping data
job_title=[]
job_location=[]
company_name=[]


#scraping the job-titles
titles=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
for i in titles:
    if i.text is None :
        job_title.append("--") 
    else:
        job_title.append(i.text)

time.sleep(4)
#scraping the job-location
locations=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
for i in locations:
    if i.text is None :
        job_location.append("--") 
    else:
        job_location.append(i.text)
        
time.sleep(4)        
#scraping the company_name 
companies=driver.find_elements_by_xpath("//div[@class='mt-7 companyInfo subheading lh16']/a")
for i in companies:
    if i.text is None :
        company_name.append("--") 
    else:
        company_name.append(i.text)

In [9]:
# creating the dataframe from the scraped data and taking only first 10 jobs
df=pd.DataFrame({"job_title":job_title[0:10],"company_name":company_name[0:10],"job_location":job_location[0:10]})
df

,job_title,company_name,job_location
0,Sr. Product Data Scientist,Uber,Bangalore/Bengaluru
1,"Sr. Data Scientist, Digital Services Analytics",(468 Reviews),Bangalore/Bengaluru
2,Senior Data Scientist,Dell,"Chennai, Bangalore/Bengaluru"
3,HCL Tech Opening - Senior Data Scientist,(2067 Reviews),"Noida, Kolkata, Hyderabad/Secunderabad, Pune, ..."
4,Cognitive/AI Senior Data Scientist,Shell,Bangalore/Bengaluru
5,Sr Data Scientist,(827 Reviews),Bangalore/Bengaluru
6,Software Principal Engineer - Data Scientist,HCL,Bangalore/Bengaluru
7,"Lead - Data Analyst / Scientist ( R, Qlik, Pow...",(15869 Reviews),Bangalore/Bengaluru
8,Data Scientist 1,IBM,Bangalore/Bengaluru
9,Data Scientist,(11472 Reviews),Bangalore/Bengaluru

* Q3: In this question you have to scrape data using the filters available on the
webpage as shown below:
You have to use the location and salary filter.
You have to scrape data for “Data Scientist” designation for first 10 job results.
You have to scrape the job-title, job-location, company_name,
experience_required.
The location filter to be used is “Delhi/NCR”
The salary filter to be used is “3-6” lakhs
The task will be done as shown in the below steps:
1. first get the webpage https://www.naukri.com/
2. Enter “Data Scientist” in “Skill,Designations,Companies” field .
3. Then click the search button.
4. Then apply the location filter and salary filter by checking the respective boxes
4. Then scrape the data for the first 10 jobs results you get.
5. Finally create a dataframe of the scraped data.

In [18]:
url = "https://www.naukri.com/"
driver.get(url)
time.sleep(6)

# entering “Data Scientist” in “Skill,Designations,Companies” field

search_field_designation=driver.find_element_by_class_name("suggestor-input ")   #job  search bar
search_field_designation.send_keys("Data Scientist")

# clicking the search button
search_button=driver.find_element_by_xpath("/html/body/div/div[2]/div[3]/div/div/div[6]")
search_button.click()


# creating empty lists for scraping data
job_title=[]
job_location=[]
company_name=[]
experience_required=[]


time.sleep(3)
#finding the delhi/ncr check box
loc=driver.find_element_by_xpath("/html/body/div[1]/div[3]/div[2]/section[1]/div[2]/div[3]/div[2]/div[3]/label/i")
loc.click()

time.sleep(2)
# finding the salary check box
slry_box = driver.find_element_by_xpath("/html/body/div[1]/div[3]/div[2]/section[1]/div[2]/div[4]/div[2]/div[1]/label/i")
slry_box.click()

time.sleep(3)
#scraping the job-titles
titles=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']"
for i in titles:
    if i.text is None :
        job_title.append("--") 
    else:
        job_title.append(i.text)
        

time.sleep(3)
#scraping the job-location
locations=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
for i in locations
    if i.text is None :
        job_location.append("--") 
    else:
        job_location.append(i.text)
        

time.sleep(3)
#scraping the company_name 
companies=driver.find_elements_by_xpath("//div[@class='mt-7 companyInfo subheading lh16']/a")
for i in companies:
    if i.text is None :
        company_name.append("--") 
    else:
        company_name.append(i.text)
        

time.sleep(3)
#scraping the experience_required 
experience=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span[1]")
for i in experience:
    if i.text is None :
            experience_required.append("--") 
    else:
            experience_required.append(i.text)
            
time.sleep(3)            
 # creating the dataframe from the scraped data and taking only first 10 jobs
df=pd.DataFrame({"job_title":job_title[0:10],"experience_required":experience_required[0:10],"company_name":company_name[0:10],
                 "job_location":job_location[0:10]})
df

SyntaxError: invalid syntax (<ipython-input-18-b6676c24c440>, line 35)

Q4 : Scrape data of first 100 sunglasses listings on flipkart.com. You have to
scrape four attributes:
1. Brand
2. Product Description
3. Price 
- To scrape 
the data you have to go through following steps:
1. Go to flipkart webpage by url https://www.flipkart.com/
2. Enter “sunglasses” in the search field where “search for products, brands and
more” is written and click the search icon
3. after that you will reach to a webpage having a lot of sunglasses. From this page
you can scrap the required data as usual.
4. after scraping data from the first page, go to the “Next” Button at the bottom of
the page , then click on it

In [21]:
url = "https://www.flipkart.com/"
driver.get(url)

In [23]:
#locating the search bar
search_bar=driver.find_element_by_class_name("_3704LK")
search_bar.send_keys('sunglasses')

time.sleep(2)
#locating the button and clicking it toh search for sunglasses
button=driver.find_element_by_class_name('L0Z3Pu')
button.click()

In [24]:
#creating the empty list
brand=[]
description=[]
price=[]


time.sleep(3)

#scrapping the required details
start=0
end=3
for page in range(start,end):#for loop for scrapping 4 page
    brands=driver.find_elements_by_class_name('_2WkVRV')#scraping brands name by class name='_2WkVRV'
    for i in brands:
        brand.append(i.text)#appending the text in Brand list
    desc=driver.find_elements_by_xpath('//a[@class="IRpwTa" or @class="IRpwTa _2-ICcC"]')#scraping description from the xpath
    for i in desc:
        description.append(i.text)#appending the description in list
    prices=driver.find_elements_by_xpath("//div[@class='_30jeq3']")# scraping the price from the xpath
    for i in prices:
        price.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [25]:
#creating a dataframe
df=pd.DataFrame({'Brand':brand,
                'Description':description,
                'Price':price})
#printing dataframe
df

            Brand                                        Description Price
0            SRPM             UV Protection Wayfarer Sunglasses (50)  ₹148
1        Fastrack      UV Protection Wayfarer Sunglasses (Free Size)  ₹319
2          SUNBEE  UV Protection, Polarized Wayfarer Sunglasses (...  ₹193
3          GANSTA              UV Protection Aviator Sunglasses (57)  ₹234
4        Fastrack  Gradient, UV Protection Wayfarer Sunglasses (F...  ₹424
..            ...                                                ...   ...
115     ROYAL SON                   Mirrored Aviator Sunglasses (55)  ₹329
116  Singco India  Mirrored, UV Protection, Riding Glasses Wayfar...  ₹245
117     New Specs   UV Protection Rectangular Sunglasses (Free Size)  ₹113
118     New Specs  UV Protection, Others Rectangular Sunglasses (...  ₹130
119     ROYAL SON   UV Protection Rectangular Sunglasses (Free Size)  ₹424

[120 rows x 3 columns]

Q5: Scrape 100 reviews data from flipkart.com for iphone11 phone. You have to 
go the link: https://www.flipkart.com/apple-iphone-11-black-64-gb-includesearpods-poweradapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace.
you have to scrape the below mention attributes.
These are 
1. Rating 
2. Review_summary 
3. Full review
- You have to scrape this data for first 100 reviews

In [26]:
url = "https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART"
driver.get(url)

time.sleep(2)

# Creating empty list
urls=[]
short_review=[]
complete_review=[]
stars=[]
time.sleep(2)

#scraping 10 pages url
url_1 = driver.find_elements_by_xpath("//a[@class='ge-49M _2Kfbh8']")
for i in url_1:
    urls.append(i.get_attribute('href'))
url_2 = driver.find_elements_by_xpath("//a[@class='ge-49M']")
for i in url_2:
    urls.append(i.get_attribute('href'))
time.sleep(4)


for i in urls:
    driver.get(i)
    #for scrapping the number of stars
    for j in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]"):
        stars.append(j.text)
    #for scrapping the short review
    for k in driver.find_elements_by_xpath("//p[@class='_2-N8zT']"):
        short_review.append(k.text)
    #for scrapping the complete review
    for l in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
        complete_review.append(l.text)
        
        
        
#Combining all the lists into a single dataframe
df=pd.DataFrame({'Number of Stars': stars,
                'Short Review': short_review,
               'Full Review': complete_review})
df

,Number of Stars,Short Review,Full Review
0,5,Brilliant,The Best Phone for the Money\n\nThe iPhone 11 ...
1,5,Simply awesome,Really satisfied with the Product I received.....
2,5,Best in the market!,Great iPhone very snappy experience as apple k...
3,5,Perfect product!,Amazing phone with great cameras and better ba...
4,5,Fabulous!,This is my first iOS phone. I am very happy wi...
5,5,Worth every penny,Previously I was using one plus 3t it was a gr...
6,5,Great product,Amazing Powerful and Durable Gadget.\n\nI’m am...
7,5,Highly recommended,What a camera .....just awesome ..you can feel...
8,4,Good choice,So far it’s been an AMAZING experience coming ...
9,5,Worth every penny,"i11 is worthy to buy, too much happy with the ..."
10,5,Simply awesome,It's very high performances devise i am like t...
11,5,Fabulous!,I can say I'm damn impressed with iPhone 11. A...
12,5,Just wow!,Best in class. Battery backup is good especial...
13,1,Absolute rubbish!,Products damage
14,5,Great product,Well you all know the specifications . One of ...
15,5,Excellent,A perfect phone and a good battery super camer...
16,1,Worthless,New Phone worked for 2 weeks. After it gone de...
17,5,Mind-blowing purchase,First thanks to Flipkart for this amazing deal...
18,5,Mind-blowing purchase,This will help you more. See if you are planni...
19,5,Super!,This is my first ever iPhone.\nAnd I truly don...
20,5,Excellent,Amazing camera and feel super machine I am not...
21,5,Wonderful,Superfast delivery by Flipkart. Thanks.\n\n1. ...
22,5,Awesome,Can’t beat the software and hardware integrati...
23,5,Perfect product!,Worth the money’ starting first from its perfo...
24,5,Terrific purchase,Its Very awesome product working and good came...
25,3,Does the job,phone is good but in display is 720p lcd in th...
26,5,Just wow!,Great iphone.\nI am writing this review after ...
27,5,Terrific purchase,finally an iPhone with very nice battery backu...
28,5,Worth every penny,iPhone is delivered on time. Display is great ...
29,5,Mind-blowing purchase,"beautiful shining, battery performance is too ..."

Q6:Scrape data for first 100 sneakers you find when you visit flipkart.comand search for “sneakers” in the search field.You have to scrape 4 attributes of each sneaker :
1. Brand
2. Product Description
3. Price
-  Also note that all the steps required during scraping should be done through code only and not manually.

In [27]:
url = "https://www.flipkart.com/"
driver.get(url)

In [28]:
#close log_in window
log_in_pop_up = driver.find_element_by_xpath("//button[@class='_2KpZ6l _2doB4z']")
log_in_pop_up.click()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[@class='_2KpZ6l _2doB4z']"}
  (Session info: chrome=99.0.4844.51)
Stacktrace:
Backtrace:
	Ordinal0 [0x00B47AC3+2587331]
	Ordinal0 [0x00ADADD1+2141649]
	Ordinal0 [0x009D3BB8+1063864]
	Ordinal0 [0x00A001CE+1245646]
	Ordinal0 [0x00A003CB+1246155]
	Ordinal0 [0x00A2A612+1418770]
	Ordinal0 [0x00A186D4+1345236]
	Ordinal0 [0x00A28A0A+1411594]
	Ordinal0 [0x00A184A6+1344678]
	Ordinal0 [0x009F53F6+1201142]
	Ordinal0 [0x009F62E6+1204966]
	GetHandleVerifier [0x00CEDF22+1680738]
	GetHandleVerifier [0x00DA0DBC+2413564]
	GetHandleVerifier [0x00BDD151+563089]
	GetHandleVerifier [0x00BDBF13+558419]
	Ordinal0 [0x00AE081E+2164766]
	Ordinal0 [0x00AE5508+2184456]
	Ordinal0 [0x00AE5650+2184784]
	Ordinal0 [0x00AEF5BC+2225596]
	BaseThreadInitThunk [0x76AE6359+25]
	RtlGetAppContainerNamedObjectPath [0x775A87A4+228]
	RtlGetAppContainerNamedObjectPath [0x775A8774+180]

In [ ]:
#locating the search bar
search_bar=driver.find_element_by_class_name("_3704LK")
search_bar.clear()
search_bar.send_keys('sneakers')

time.sleep(2)
#locating the button and clicking it to search for sneakers
button=driver.find_element_by_class_name('L0Z3Pu')
button.click()

In [ ]:
#creating the empty list
brand=[]
description=[]
price=[]

start=0
end=4
for page in range(start,end):#for loop for scrapping 4 page
    brands=driver.find_elements_by_class_name('_2WkVRV')#scraping brands name by class name='_2WkVRV'
    for i in brands:
        brand.append(i.text)#appending the text in Brand list
    prices=driver.find_elements_by_xpath("//div[@class='_30jeq3']")# scraping the price from the xpath
    for i in prices:
        price.append(i.text)
    desc=driver.find_elements_by_xpath('//a[@class="IRpwTa" or @class="IRpwTa _2-ICcC"]')#scraping description from the xpath
    for i in desc:
        description.append(i.text)
        
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [ ]:
#creating a dataframe
df=pd.DataFrame({'Brand':brand[:100],
                'Description':description[:100],
                'Price':price[:100]})
#printing dataframe
df

Q7."https://www.myntra.com/shoes". 
Set price filter "Rs 7187 to Rs 14125" and color filter to "Black" and then scrap 100 shoes data. The data should include "Brand" of shoes, shoe short-description and price. Please not: Everything should done through code even the filtering for sneakers as well.

In [ ]:
url = "https://www.myntra.com/shoes%22"
driver.get(url)

time.sleep(2)

#clicking on price filter
price_button = driver.find_element_by_xpath("//ul[@class='price-list']/li[2]")
price_button.click()

#clicking on black colour
black_button = driver.find_element_by_xpath("/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[6]/ul/li[1]/label/div")
black_button.click()

In [ ]:
#creating empty lists
shoe_names=[]
s_desc=[]
short_desc=[]
price=[]
page_urls = []

time.sleep(4)
# scrape next pages urls
nxt_page = driver.find_elements_by_xpath("//ul[@class='pagination-container']/li/a")
for i in nxt_page:
    page_urls.append(i.get_attribute('href'))
    

for url in page_urls[:3]:
    driver.get(url)
    Names=driver.find_elements_by_xpath("//div[@class='product-productMetaInfo']/h3")  #for scrapping shoe brand names
    for i in Names:
        shoe_names.append(i.text)
    
    desc=driver.find_elements_by_xpath("//div[@class='product-productMetaInfo']/h4") #for scrapping shoe short-description
    for i in desc:
        s_desc.append(i.text)
    #As, the s_desc list contain blank description in every alternate index, so removing the blank or null description
    for j in range(0,len(s_desc),2):
        short_desc.append(s_desc[j])
    
    rs=driver.find_elements_by_xpath("//div[@class='product-price']")  #for scrapping shoe prices
    for i in rs:
        price.append(i.text)    
        
df=pd.DataFrame({'Brand': shoe_names[:100],'Short-description': short_desc[:100],'Price': price[:100]})
df

Q8:  Go to webpage https://www.amazon.in/Enter “Laptop” in the search field and then click the search icon.Then set CPU Type filter to “Intel Core i7”
After setting the filters scrape first 10 laptops data.You have to scrape 3 attributes for each laptop:
1. title
2. Ratings
3. Price

In [ ]:
url = "https://www.amazon.in/ref=nav_logo"
driver.get(url)


#creating the empty list
Title=[]
Ratings=[]
price=[]

time.sleep(2)
#locating the search bar
search_bar = driver.find_element_by_id("twotabsearchtextbox")    # Locating searc_bar by id
search_bar.clear()                                               # clearing search_bar
search_bar.send_keys("laptops")                                   # sending user input to search bar
search_button = driver.find_element_by_xpath('//span[@id="nav-search-submit-text"]')       # Locating search_button by xpath
search_button.click()    

time.sleep(2)
#locating the core i7 filter
filter_button=driver.find_elements_by_xpath("//a[@class='a-link-normal s-navigation-item']/span")
for i in filter_button:
    if i.text=='Intel Core i7':
        i.click()
        break
        
        
#Scrapping Titles
titles=driver.find_elements_by_xpath("//span[@class='a-size-medium a-color-base a-text-normal']")
for i in titles[:10]:
    Title.append(i.text)
    
    
#scrapping Price
prices=driver.find_elements_by_xpath("//span[@class='a-price-whole']")
for i in prices[:10]:
    price.append(i.text)

#locating Ratings
urls=driver.find_elements_by_xpath("//a[@class='a-link-normal a-text-normal']")#collecting urls of all the laptop
UR=[]
for i in urls[:10]:
    UR.append(i.get_attribute('href'))#getting the url of first 10 laptops
for url in UR:#loop for every laptop in the list
    driver.get(url)
    try:                  #exception handling for nosuchelementexception                                                    #click the rating link found
        rating=driver.find_element_by_xpath("//span[@class='a-size-base a-nowrap']//span")#locating the rating
        Ratings.append(rating.text)#appending the ratings in Ratings list
        
    except NoSuchElementException:
        Ratings.append("NO rating")#appending the No rating if no rating is there
        
#creating a dataframe
df=pd.DataFrame({'Title':Title,
                'Price':price,
                'Ratings':Ratings})
#printing dataframe
df

Q9: Write a python program to scrape data for first 10 job results for Data Scientist Designation in Noida 
location. You have to scrape company name, No. of days ago when job was posted, Rating of the company.
This task will be done in following steps:
1. First get the webpage https://www.ambitionbox.com/
2. Click on the Job option as shown in the image
3. After reaching to the next webpage, In place of “Search by Designations, Companies, Skills” enter “Data Scientist” and click on search button.
4. You will reach to the following web page click on location and in place of “Search location” enter “Noida” and select location “Noida”.
5. Then scrape the data for the first 10 jobs results you get on the above shown page.
6. Finally create a dataframe of the scraped data.

In [ ]:
driver.get('https://www.ambitionbox.com/')

In [ ]:
job_option = driver.find_element_by_xpath("//a[@class='link jobs']")
job_option.click()

search_job = driver.find_element_by_xpath('/html/body/div/div/div/div[2]/div[1]/div/div/div/div/span/input')
search_job.send_keys('Data Scientist')

search_btn = driver.find_element_by_xpath("/html/body/div/div/div/div[2]/div[1]/div/div/div/button/span")
search_btn.click()

select_location = driver.find_element_by_xpath("/html/body/div/div/div/div[2]/div[2]/div[1]/div/div/div/div[2]/div[1]/p")
select_location.click()

location = driver.find_element_by_xpath('/html/body/div/div/div/div[2]/div[2]/div[1]/div/div/div/div[2]/div[2]/div/div[2]/input')
location.send_keys('Noida')

select_Noida = driver.find_element_by_xpath("/html/body/div/div/div/div[2]/div[2]/div[1]/div/div/div/div[2]/div[2]/div/div[3]/div/div/div[1]/label")
select_Noida.click()

In [ ]:
#fetching the top 10 data
#top 10 company name
company_name = driver.find_elements_by_xpath("//p[@class='company body-medium']")
companies=[]
for i in company_name[0:10]:
    companies.append(i.text)
    
#number of days ago job was posted    
no_of_days = driver.find_elements_by_xpath("//div[@class='other-info']/span[1]")
no_of_days_ago=[]
for i in no_of_days[0:10] :
    no_of_days_ago.append(i.text)

#ratings given to the company
ratings = driver.find_elements_by_xpath("//div[@class='info']/div/div/a/span")
company_rating=[]
for i in ratings[0:10] :
    company_rating.append(i.text)

In [ ]:
#creating dataframe
data = list(zip(companies,no_of_days_ago,company_rating))

import pandas as pd
df = pd.DataFrame(data,columns=['companies','no_of_days_ago','company_rating'])

df.head(10)

Q10: Write a python program to scrape the salary data for Data Scientist designation.
You have to scrape Company name, Number of salaries, Average salary, Minsalary, Max Salary.
The above task will be, done as shown in the below steps:
1. First get the webpage https://www.ambitionbox.com/
2. Click on the salaries option as shown in the image.
3. After reaching to the following webpage, In place of “Search Job Profile” enters “Data Scientist” and then click on “Data Scientist”.
4. Scrape the data for the first 10 companies. Scrape the company name, total salary record, average salary, minimum salary, maximum salary, experience required.
5. Store the data in a dataframe.

In [ ]:
driver.get('https://www.ambitionbox.com/')

In [ ]:
salary_option = driver.find_element_by_xpath("//a[@class='link salaries']")
salary_option.click()

job_profile = driver.find_element_by_xpath('/html/body/div/div/div/main/section[1]/div[2]/div[1]/span/input')
job_profile.send_keys('Data Scientist')

select_DS = driver.find_element_by_xpath("/html/body/div/div/div/main/section[1]/div[2]/div[1]/span/div/div/div[1]/div/div/p")
select_DS.click()

In [ ]:
#company name
company_name = driver.find_elements_by_xpath("//div[@class='name']/a")
companies=[]
for i in company_name[0:10]:
    companies.append(i.text) 
    
#salary
salary = driver.find_elements_by_xpath("//div[@class='name']/span")
salary_record=[]
for i in salary[0:10]:
    salary_record.append(i.text)

#average salary
Average = driver.find_elements_by_xpath("//p[@class='averageCtc']")
avg_salary=[]
for i in Average[0:10]:
    avg_salary.append(i.text)
    
#minimum salary
min_salary = driver.find_elements_by_xpath("//div[@class='salary-values']/div[1]")
min_salary_range=[]
for i in min_salary[0:10]:
    min_salary_range.append(i.text)
    
#maximum salary
max_salary = driver.find_elements_by_xpath("//div[@class='salary-values']/div[2]")
max_salary_range=[]
for i in max_salary[0:10]:
    max_salary_range.append(i.text)
    
#experience required
experience = driver.find_elements_by_xpath("//div[@class='salaries sbold-list-header']")
experience_required=[]
for i in experience[0:10]:
    experience_required.append(i.text.split('\n')[2])

In [ ]:
data = list(zip(companies,salary_record,avg_salary,min_salary_range,max_salary_range,experience_required))
import pandas as pd
df = pd.DataFrame(data,columns=['companies','salary_record','avg_salary','min_salary_range','max_salary_range','experience_required'])
df.head(10)